// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipFormat } from "./ClipFormat";

export interface ClipCreationOptions { from: string, to: string, start: number, end: number, video_bitrate: number, audio_bitrate: number, framerate: number, speed: number, resolution: number, mute: boolean, format: ClipFormat, }