// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DownloadProgress { progress: number, total_size: bigint, downloaded: bigint, speed: number, }