// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Limitation } from "./Limitation";

export interface OutputFormat { name: string, extension: string, preset: string, limitations: Array<Limitation>, }