// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export interface Progress { frame: bigint | null, fps: number | null, total_size: bigint | null, out_time: number | null, dup_frames: bigint | null, drop_frames: bigint | null, speed: number | null, status: Status, }